dist: trusty
language: python

# Define which python version to build against.
# As blender comes bundled with it's own python the version does not really matter
python:
  - "3.4"

before_install:
  # update apt-gets repository sources
  - sudo apt-get update -qq

  # install blender from official sources.
  # This will most propably install an outdated blender version,
  # but it will resolve all system dependencies blender has to be able to run.
  - sudo apt-get install -y blender

  # Download and LuxCore deps
  - git clone https://github.com/LuxCoreRender/LuxCore.git
  - cd LuxCore

  # Install deps
  - sudo apt-get install -y git cmake g++ flex bison libbz2-dev libopenimageio-dev libtiff5-dev libpng12-dev libgtk-3-dev libopenexr-dev libgl1-mesa-dev python3-dev python3-pip
  # Install Boost
  - wget https://github.com/LuxCoreRender/LinuxCompileDeps/releases/download/luxcorerender_v2.0beta1/boost_1_56_0-bin.tar.gz
  - tar zxf boost_1_56_0-bin.tar.gz
  - export LD_LIBRARY_PATH=`pwd`/boost_1_56_0-bin/lib:$LD_LIBRARY_PATH
  # Install Embree
  - wget https://github.com/embree/embree/releases/download/v2.17.1/embree-2.17.1.x86_64.linux.tar.gz
  - tar zxf embree-2.17.1.x86_64.linux.tar.gz
  - export LD_LIBRARY_PATH=`pwd`/embree-2.17.1.x86_64.linux/lib:$LD_LIBRARY_PATH
  - cd ..

install:
  # Compile LuxCore
  - cd LuxCore
  - cmake -D BOOST_SEARCH_PATH=`pwd`/boost_1_56_0-bin -D EMBREE_SEARCH_PATH=`pwd`/embree-2.17.1.x86_64.linux -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.4m.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.4m .
  - make -j 2
  - cd ..

  # Copy LuxCore binaries to BlendLuxCore/bin directory
  - cd bin
  - ./get_binaries.py ../LuxCore --overwrite
  - cd ..

  # create temp directory where we store a recent blender version
  - mkdir tmp && cd tmp

  # download the blender version we want to test against
  # TODO: for now this points to buildbot, but it should point to 2.79a once that gets out
  - wget https://builder.blender.org/download/blender-2.79-c38ebf93e35-linux-glibc219-x86_64.tar.bz2

  # Extract the archive
  - tar jxf blender-2.79-c38ebf93e35-linux-glibc219-x86_64.tar.bz2

  # rename the extracted folder to "blender" for easier reference
  - mv blender-2.79-c38ebf93e35-linux-glibc219-x86_64 blender

  # remove the archive, we do not need it anymore
  - rm blender-2.79-c38ebf93e35-linux-glibc219-x86_64.tar.bz2

  # go back to root directory
  - cd ..

  # now create a symlink to the addon within blenders addons directory
  # this is important, because otherwhise blender would not be able to load the addon
  - ln -s ${PWD} ${PWD}/tmp/blender/2.79/scripts/addons/BlendLuxCore

# Finally start our test runner passing it the blender executable from the downloaded blender release
script:
  - cd tests
  - ./testrunner.py ../tmp/blender/blender